FROM python:3.10

# Set working directory
WORKDIR /usr/src/app

# Copying and installing python packages
COPY requirements.txt /
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /requirements.txt && pip install --no-cache-dir gunicorn

# Copying current local app directory to container
COPY /app /usr/src/app/

# Non root user
RUN useradd -m appUser
USER appUser

# Running the dash
CMD gunicorn --bind 0.0.0.0:$PORT app:server